client: applicationclass.o bitmapclass.o cameraclass.o fontclass.o fontshaderclass.o inputclass.o lightclass.o lightshaderclass.o main.o modelclass.o openglclass.o systemclass.o textclass.o textureclass.o textureshaderclass.o
	g++ -o client applicationclass.o bitmapclass.o cameraclass.o fontclass.o fontshaderclass.o inputclass.o lightclass.o lightshaderclass.o main.o modelclass.o openglclass.o systemclass.o textclass.o textureclass.o textureshaderclass.o -l GL -l X11

applicationclass.o: applicationclass.cpp
	g++ -c applicationclass.cpp

bitmapclass.o: bitmapclass.cpp
	g++ -c bitmapclass.cpp

cameraclass.o: cameraclass.cpp
	g++ -c cameraclass.cpp

fontclass.o: fontclass.cpp
	g++ -c fontclass.cpp

fontshaderclass.o: fontshaderclass.cpp
	g++ -c fontshaderclass.cpp

inputclass.o: inputclass.cpp
	g++ -c inputclass.cpp

lightclass.o: lightclass.cpp
	g++ -c lightclass.cpp

lightshaderclass.o: lightshaderclass.cpp
	g++ -c lightshaderclass.cpp

main.o: main.cpp
	g++ -c main.cpp

modelclass.o: modelclass.cpp
	g++ -c modelclass.cpp

openglclass.o: openglclass.cpp
	g++ -c openglclass.cpp

systemclass.o: systemclass.cpp
	g++ -c systemclass.cpp

textclass.o: textclass.cpp
	g++ -c textclass.cpp

textureclass.o: textureclass.cpp
	g++ -c textureclass.cpp

textureshaderclass.o: textureshaderclass.cpp
	g++ -c textureshaderclass.cpp
