client: applicationclass.o blurclass.o blurshaderclass.o cameraclass.o heatclass.o heatshaderclass.o inputclass.o lightclass.o lightshaderclass.o main.o modelclass.o openglclass.o orthowindowclass.o rendertextureclass.o systemclass.o textureclass.o textureshaderclass.o timerclass.o
	g++ -o client applicationclass.o blurclass.o blurshaderclass.o cameraclass.o heatclass.o heatshaderclass.o inputclass.o lightclass.o lightshaderclass.o main.o modelclass.o openglclass.o orthowindowclass.o rendertextureclass.o systemclass.o textureclass.o textureshaderclass.o timerclass.o -l GL -l X11

applicationclass.o: applicationclass.cpp
	g++ -c applicationclass.cpp

blurclass.o: blurclass.cpp
	g++ -c blurclass.cpp

blurshaderclass.o: blurshaderclass.cpp
	g++ -c blurshaderclass.cpp

cameraclass.o: cameraclass.cpp
	g++ -c cameraclass.cpp

heatclass.o: heatclass.cpp
	g++ -c heatclass.cpp

heatshaderclass.o: heatshaderclass.cpp
	g++ -c heatshaderclass.cpp

inputclass.o: inputclass.cpp
	g++ -c inputclass.cpp

lightclass.o: lightclass.cpp
	g++ -c lightclass.cpp

lightshaderclass.o: lightshaderclass.cpp
	g++ -c lightshaderclass.cpp

main.o: main.cpp
	g++ -c main.cpp

modelclass.o: modelclass.cpp
	g++ -c modelclass.cpp

openglclass.o: openglclass.cpp
	g++ -c openglclass.cpp

orthowindowclass.o: orthowindowclass.cpp
	g++ -c orthowindowclass.cpp

rendertextureclass.o: rendertextureclass.cpp
	g++ -c rendertextureclass.cpp

systemclass.o: systemclass.cpp
	g++ -c systemclass.cpp

textureclass.o: textureclass.cpp
	g++ -c textureclass.cpp

textureshaderclass.o: textureshaderclass.cpp
	g++ -c textureshaderclass.cpp

timerclass.o: timerclass.cpp
	g++ -c timerclass.cpp
