client: applicationclass.o cameraclass.o displayplaneclass.o inputclass.o main.o modelclass.o openglclass.o rendertextureclass.o systemclass.o textureclass.o textureshaderclass.o
	g++ -o client applicationclass.o cameraclass.o displayplaneclass.o inputclass.o main.o modelclass.o openglclass.o rendertextureclass.o systemclass.o textureclass.o textureshaderclass.cpp -l GL -l X11

applicationclass.o: applicationclass.cpp
	g++ -c applicationclass.cpp

cameraclass.o: cameraclass.cpp
	g++ -c cameraclass.cpp

displayplaneclass.o: displayplaneclass.cpp
	g++ -c displayplaneclass.cpp

inputclass.o: inputclass.cpp
	g++ -c inputclass.cpp

main.o: main.cpp
	g++ -c main.cpp

modelclass.o: modelclass.cpp
	g++ -c modelclass.cpp

openglclass.o: openglclass.cpp
	g++ -c openglclass.cpp

rendertextureclass.o: rendertextureclass.cpp
	g++ -c rendertextureclass.cpp

systemclass.o: systemclass.cpp
	g++ -c systemclass.cpp

textureclass.o: textureclass.cpp
	g++ -c textureclass.cpp

textureshaderclass.o: textureshaderclass.cpp
	g++ -c textureshaderclass.cpp
