<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>RastertekCS.OpenGL.Tutorial05</RootNamespace>
    <AssemblyName>Tutorial05</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Silk.NET.OpenGL" Version="2.22.0" />
    <PackageReference Include="Silk.NET.Windowing" Version="2.22.0" />
    <PackageReference Include="Silk.NET.Input" Version="2.22.0" />
    <PackageReference Include="Silk.NET.Maths" Version="2.22.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Shaders\Texture.vs" CopyToOutputDirectory="PreserveNewest" />
    <None Update="Shaders\Texture.ps" CopyToOutputDirectory="PreserveNewest" />
    <None Update="Textures\Stone01.tga" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
