client: applicationclass.o cameraclass.o fontclass.o fontshaderclass.o frustumclass.o inputclass.o lightclass.o lightshaderclass.o main.o modelclass.o modellistclass.o openglclass.o positionclass.o systemclass.o textclass.o textureclass.o timerclass.o
	g++ -o client applicationclass.o cameraclass.o fontclass.o fontshaderclass.o frustumclass.o inputclass.o lightclass.o lightshaderclass.o main.o modelclass.o modellistclass.o openglclass.o positionclass.o systemclass.o textclass.o textureclass.o timerclass.o -l GL -l X11

applicationclass.o: applicationclass.cpp
	g++ -c applicationclass.cpp

cameraclass.o: cameraclass.cpp
	g++ -c cameraclass.cpp

fontclass.o: fontclass.cpp
	g++ -c fontclass.cpp

fontshaderclass.o: fontshaderclass.cpp
	g++ -c fontshaderclass.cpp

frustumclass.o: frustumclass.cpp
	g++ -c frustumclass.cpp

inputclass.o: inputclass.cpp
	g++ -c inputclass.cpp

lightclass.o: lightclass.cpp
	g++ -c lightclass.cpp

lightshaderclass.o: lightshaderclass.cpp
	g++ -c lightshaderclass.cpp

main.o: main.cpp
	g++ -c main.cpp

modelclass.o: modelclass.cpp
	g++ -c modelclass.cpp

modellistclass.o: modellistclass.cpp
	g++ -c modellistclass.cpp

openglclass.o: openglclass.cpp
	g++ -c openglclass.cpp

positionclass.o: positionclass.cpp
	g++ -c positionclass.cpp

systemclass.o: systemclass.cpp
	g++ -c systemclass.cpp

textclass.o: textclass.cpp
	g++ -c textclass.cpp

textureclass.o: textureclass.cpp
	g++ -c textureclass.cpp

timerclass.o: timerclass.cpp
	g++ -c timerclass.cpp
