<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>RastertekCS.Tools.ObjToModel</RootNamespace>
    <AssemblyName>ObjToModel</AssemblyName>
  </PropertyGroup>

</Project>
