client: applicationclass.o cameraclass.o fontclass.o fontshaderclass.o inputclass.o main.o openglclass.o systemclass.o textclass.o textureclass.o xboxinputclass.o
	g++ -o client applicationclass.o cameraclass.o fontclass.o fontshaderclass.o inputclass.o main.o openglclass.o systemclass.o textclass.o textureclass.o xboxinputclass.o -l GL -l X11

applicationclass.o: applicationclass.cpp
	g++ -c applicationclass.cpp

cameraclass.o: cameraclass.cpp
	g++ -c cameraclass.cpp

fontclass.o: fontclass.cpp
	g++ -c fontclass.cpp

fontshaderclass.o: fontshaderclass.cpp
	g++ -c fontshaderclass.cpp

inputclass.o: inputclass.cpp
	g++ -c inputclass.cpp

main.o: main.cpp
	g++ -c main.cpp

openglclass.o: openglclass.cpp
	g++ -c openglclass.cpp

systemclass.o: systemclass.cpp
	g++ -c systemclass.cpp

textclass.o: textclass.cpp
	g++ -c textclass.cpp

textureclass.o: textureclass.cpp
	g++ -c textureclass.cpp

xboxinputclass.o: xboxinputclass.cpp
	g++ -c xboxinputclass.cpp
