client: applicationclass.o cameraclass.o fontclass.o fontshaderclass.o fpsclass.o inputclass.o main.o openglclass.o positionclass.o shadermanagerclass.o systemclass.o terrainclass.o terrainshaderclass.o textclass.o textureclass.o timerclass.o userinterfaceclass.o zoneclass.o
	g++ -o client applicationclass.o cameraclass.o fontclass.o fontshaderclass.o fpsclass.o inputclass.o main.o openglclass.o positionclass.o shadermanagerclass.o systemclass.o terrainclass.o terrainshaderclass.o textclass.o textureclass.o timerclass.o userinterfaceclass.o zoneclass.o -l GL -l X11

applicationclass.o: applicationclass.cpp
	g++ -c applicationclass.cpp

cameraclass.o: cameraclass.cpp
	g++ -c cameraclass.cpp

fontclass.o: fontclass.cpp
	g++ -c fontclass.cpp

fontshaderclass.o: fontshaderclass.cpp
	g++ -c fontshaderclass.cpp

fpsclass.o: fpsclass.cpp
	g++ -c fpsclass.cpp

inputclass.o: inputclass.cpp
	g++ -c inputclass.cpp

main.o: main.cpp
	g++ -c main.cpp

openglclass.o: openglclass.cpp
	g++ -c openglclass.cpp

positionclass.o: positionclass.cpp
	g++ -c positionclass.cpp

shadermanagerclass.o: shadermanagerclass.cpp
	g++ -c shadermanagerclass.cpp

systemclass.o: systemclass.cpp
	g++ -c systemclass.cpp

terrainclass.o: terrainclass.cpp
	g++ -c terrainclass.cpp

terrainshaderclass.o: terrainshaderclass.cpp
	g++ -c terrainshaderclass.cpp

textclass.o: textclass.cpp
	g++ -c textclass.cpp

textureclass.o: textureclass.cpp
	g++ -c textureclass.cpp

timerclass.o: timerclass.cpp
	g++ -c timerclass.cpp

userinterfaceclass.o: userinterfaceclass.cpp
	g++ -c userinterfaceclass.cpp

zoneclass.o: zoneclass.cpp
	g++ -c zoneclass.cpp
