<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>RastertekCS.Windows.Tutorial45</RootNamespace>
    <AssemblyName>Tutorial45</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Silk.NET.Direct3D11" Version="2.23.0" />
    <PackageReference Include="Silk.NET.Direct3D.Compilers" Version="2.23.0" />
    <PackageReference Include="Silk.NET.DXGI" Version="2.23.0" />
    <PackageReference Include="Silk.NET.Windowing" Version="2.23.0" />
    <PackageReference Include="Silk.NET.Input" Version="2.23.0" />
    <PackageReference Include="Silk.NET.Maths" Version="2.23.0" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Shaders\depth.vs" CopyToOutputDirectory="PreserveNewest" />
    <None Update="Shaders\depth.ps" CopyToOutputDirectory="PreserveNewest" />
    <None Update="Shaders\transparentdepth.vs" CopyToOutputDirectory="PreserveNewest" />
    <None Update="Shaders\transparentdepth.ps" CopyToOutputDirectory="PreserveNewest" />
    <None Update="Shaders\shadow.vs" CopyToOutputDirectory="PreserveNewest" />
    <None Update="Shaders\shadow.ps" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\Assets\Data\dirt01.tga" Link="Data\dirt01.tga" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\Assets\Data\trunk001.tga" Link="Data\trunk001.tga" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\Assets\Data\leaf001.tga" Link="Data\leaf001.tga" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\Assets\Models\plane01.txt" Link="Models\plane01.txt" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\Assets\Models\trunk001.txt" Link="Models\trunk001.txt" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\Assets\Models\leaf001.txt" Link="Models\leaf001.txt" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
