<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>RastertekCS.Windows.Tutorial04</RootNamespace>
    <AssemblyName>Tutorial04</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Silk.NET.Direct3D11" Version="2.23.0" />
    <PackageReference Include="Silk.NET.Direct3D.Compilers" Version="2.23.0" />
    <PackageReference Include="Silk.NET.DXGI" Version="2.23.0" />
    <PackageReference Include="Silk.NET.Windowing" Version="2.23.0" />
    <PackageReference Include="Silk.NET.Input" Version="2.23.0" />
    <PackageReference Include="Silk.NET.Maths" Version="2.23.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Shaders\Color.vs" CopyToOutputDirectory="PreserveNewest" />
    <None Update="Shaders\Color.ps" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
