client: applicationclass.o cameraclass.o inputclass.o main.o openglclass.o particleshaderclass.o particlesystemclass.o systemclass.o textureclass.o timerclass.o
	g++ -o client applicationclass.o cameraclass.o inputclass.o main.o openglclass.o particleshaderclass.o particlesystemclass.o systemclass.o textureclass.o timerclass.o -l GL -l X11

applicationclass.o: applicationclass.cpp
	g++ -c applicationclass.cpp

cameraclass.o: cameraclass.cpp
	g++ -c cameraclass.cpp

inputclass.o: inputclass.cpp
	g++ -c inputclass.cpp

main.o: main.cpp
	g++ -c main.cpp

openglclass.o: openglclass.cpp
	g++ -c openglclass.cpp

particleshaderclass.o: particleshaderclass.cpp
	g++ -c particleshaderclass.cpp

particlesystemclass.o: particlesystemclass.cpp
	g++ -c particlesystemclass.cpp

systemclass.o: systemclass.cpp
	g++ -c systemclass.cpp

textureclass.o: textureclass.cpp
	g++ -c textureclass.cpp

timerclass.o: timerclass.cpp
	g++ -c timerclass.cpp
