client: applicationclass.o cameraclass.o depthshaderclass.o inputclass.o lightclass.o main.o modelclass.o openglclass.o rendertextureclass.o shadowshaderclass.o systemclass.o textureclass.o
	g++ -o client applicationclass.o cameraclass.o depthshaderclass.o inputclass.o lightclass.o main.o modelclass.o openglclass.o rendertextureclass.o shadowshaderclass.o systemclass.o textureclass.o -l GL -l X11

applicationclass.o: applicationclass.cpp
	g++ -c applicationclass.cpp

cameraclass.o: cameraclass.cpp
	g++ -c cameraclass.cpp

depthshaderclass.o: depthshaderclass.cpp
	g++ -c depthshaderclass.cpp

inputclass.o: inputclass.cpp
	g++ -c inputclass.cpp

lightclass.o: lightclass.cpp
	g++ -c lightclass.cpp

main.o: main.cpp
	g++ -c main.cpp

modelclass.o: modelclass.cpp
	g++ -c modelclass.cpp

openglclass.o: openglclass.cpp
	g++ -c openglclass.cpp

rendertextureclass.o: rendertextureclass.cpp
	g++ -c rendertextureclass.cpp

shadowshaderclass.o: shadowshaderclass.cpp
	g++ -c shadowshaderclass.cpp

systemclass.o: systemclass.cpp
	g++ -c systemclass.cpp

textureclass.o: textureclass.cpp
	g++ -c textureclass.cpp
