client: applicationclass.o cameraclass.o inputclass.o lightclass.o main.o modelclass.o openglclass.o pbrshaderclass.o systemclass.o textureclass.o
	g++ -o client applicationclass.o cameraclass.o inputclass.o lightclass.o main.o modelclass.o openglclass.o pbrshaderclass.o systemclass.o textureclass.o -l GL -l X11

applicationclass.o: applicationclass.cpp
	g++ -c applicationclass.cpp

cameraclass.o: cameraclass.cpp
	g++ -c cameraclass.cpp

inputclass.o: inputclass.cpp
	g++ -c inputclass.cpp

lightclass.o: lightclass.cpp
	g++ -c lightclass.cpp

main.o: main.cpp
	g++ -c main.cpp

modelclass.o: modelclass.cpp
	g++ -c modelclass.cpp

openglclass.o: openglclass.cpp
	g++ -c openglclass.cpp

pbrshaderclass.o: pbrshaderclass.cpp
	g++ -c pbrshaderclass.cpp

systemclass.o: systemclass.cpp
	g++ -c systemclass.cpp

textureclass.o: textureclass.cpp
	g++ -c textureclass.cpp
