client: applicationclass.o cameraclass.o inputclass.o lightclass.o lightshaderclass.o main.o modelclass.o openglclass.o refractionshaderclass.o rendertextureclass.o systemclass.o textureclass.o watershaderclass.o
	g++ -o client applicationclass.o cameraclass.o inputclass.o lightclass.o lightshaderclass.o main.o modelclass.o openglclass.o refractionshaderclass.o rendertextureclass.o systemclass.o textureclass.o watershaderclass.o -l GL -l X11

applicationclass.o: applicationclass.cpp
	g++ -c applicationclass.cpp

cameraclass.o: cameraclass.cpp
	g++ -c cameraclass.cpp

inputclass.o: inputclass.cpp
	g++ -c inputclass.cpp

lightclass.o: lightclass.cpp
	g++ -c lightclass.cpp

lightshaderclass.o: lightshaderclass.cpp
	g++ -c lightshaderclass.cpp

main.o: main.cpp
	g++ -c main.cpp

modelclass.o: modelclass.cpp
	g++ -c modelclass.cpp

openglclass.o: openglclass.cpp
	g++ -c openglclass.cpp

refractionshaderclass.o: refractionshaderclass.cpp
	g++ -c refractionshaderclass.cpp

rendertextureclass.o: rendertextureclass.cpp
	g++ -c rendertextureclass.cpp

systemclass.o: systemclass.cpp
	g++ -c systemclass.cpp

textureclass.o: textureclass.cpp
	g++ -c textureclass.cpp

watershaderclass.o: watershaderclass.cpp
	g++ -c watershaderclass.cpp
