client: applicationclass.o cameraclass.o inputclass.o main.o openglclass.o orthowindowclass.o parallaxscrollclass.o scrollshaderclass.o systemclass.o textureclass.o timerclass.o
	g++ -o client applicationclass.o cameraclass.o inputclass.o main.o openglclass.o orthowindowclass.o parallaxscrollclass.o scrollshaderclass.o systemclass.o textureclass.o timerclass.o -l GL -l X11

applicationclass.o: applicationclass.cpp
	g++ -c applicationclass.cpp

cameraclass.o: cameraclass.cpp
	g++ -c cameraclass.cpp

inputclass.o: inputclass.cpp
	g++ -c inputclass.cpp

main.o: main.cpp
	g++ -c main.cpp

openglclass.o: openglclass.cpp
	g++ -c openglclass.cpp

orthowindowclass.o: orthowindowclass.cpp
	g++ -c orthowindowclass.cpp

parallaxscrollclass.o: parallaxscrollclass.cpp
	g++ -c parallaxscrollclass.cpp

scrollshaderclass.o: scrollshaderclass.cpp
	g++ -c scrollshaderclass.cpp

systemclass.o: systemclass.cpp
	g++ -c systemclass.cpp

textureclass.o: textureclass.cpp
	g++ -c textureclass.cpp

timerclass.o: timerclass.cpp
	g++ -c timerclass.cpp
