client: applicationclass.o cameraclass.o inputclass.o lightclass.o lightshaderclass.o main.o modelclass.o normalmapshaderclass.o openglclass.o shadermanagerclass.o systemclass.o textureclass.o textureshaderclass.o
	g++ -o client applicationclass.o cameraclass.o inputclass.o lightclass.o lightshaderclass.o main.o modelclass.o normalmapshaderclass.o openglclass.o shadermanagerclass.o systemclass.o textureclass.o textureshaderclass.o -l GL -l X11

applicationclass.o: applicationclass.cpp
	g++ -c applicationclass.cpp

cameraclass.o: cameraclass.cpp
	g++ -c cameraclass.cpp

inputclass.o: inputclass.cpp
	g++ -c inputclass.cpp

lightclass.o: lightclass.cpp
	g++ -c lightclass.cpp

lightshaderclass.o: lightshaderclass.cpp
	g++ -c lightshaderclass.cpp

main.o: main.cpp
	g++ -c main.cpp

modelclass.o: modelclass.cpp
	g++ -c modelclass.cpp

normalmapshaderclass.o: normalmapshaderclass.cpp
	g++ -c normalmapshaderclass.cpp

openglclass.o: openglclass.cpp
	g++ -c openglclass.cpp

shadermanagerclass.o: shadermanagerclass.cpp
	g++ -c shadermanagerclass.cpp

systemclass.o: systemclass.cpp
	g++ -c systemclass.cpp

textureclass.o: textureclass.cpp
	g++ -c textureclass.cpp

textureshaderclass.o: textureshaderclass.cpp
	g++ -c textureshaderclass.cpp
