client: applicationclass.o blurclass.o blurshaderclass.o cameraclass.o depthshaderclass.o inputclass.o lightclass.o main.o modelclass.o openglclass.o orthowindowclass.o rendertextureclass.o shadowshaderclass.o softshadowshaderclass.o systemclass.o textureclass.o textureshaderclass.o
	g++ -o client applicationclass.o blurclass.o blurshaderclass.o cameraclass.o depthshaderclass.o inputclass.o lightclass.o main.o modelclass.o openglclass.o orthowindowclass.o rendertextureclass.o shadowshaderclass.o softshadowshaderclass.o systemclass.o textureclass.o textureshaderclass.o -l GL -l X11

applicationclass.o: applicationclass.cpp
	g++ -c applicationclass.cpp

blurclass.o: blurclass.cpp
	g++ -c blurclass.cpp

blurshaderclass.o: blurshaderclass.cpp
	g++ -c blurshaderclass.cpp

cameraclass.o: cameraclass.cpp
	g++ -c cameraclass.cpp

depthshaderclass.o: depthshaderclass.cpp
	g++ -c depthshaderclass.cpp

inputclass.o: inputclass.cpp
	g++ -c inputclass.cpp

lightclass.o: lightclass.cpp
	g++ -c lightclass.cpp

main.o: main.cpp
	g++ -c main.cpp

modelclass.o: modelclass.cpp
	g++ -c modelclass.cpp

openglclass.o: openglclass.cpp
	g++ -c openglclass.cpp

orthowindowclass.o: orthowindowclass.cpp
	g++ -c orthowindowclass.cpp

rendertextureclass.o: rendertextureclass.cpp
	g++ -c rendertextureclass.cpp

shadowshaderclass.o: shadowshaderclass.cpp
	g++ -c shadowshaderclass.cpp

softshadowshaderclass.o: softshadowshaderclass.cpp
	g++ -c softshadowshaderclass.cpp

systemclass.o: systemclass.cpp
	g++ -c systemclass.cpp

textureclass.o: textureclass.cpp
	g++ -c textureclass.cpp

textureshaderclass.o: textureshaderclass.cpp
	g++ -c textureshaderclass.cpp
