<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>RastertekCS.OpenGL.Tutorial09</RootNamespace>
    <AssemblyName>Tutorial09</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Silk.NET.OpenGL" Version="2.22.0" />
    <PackageReference Include="Silk.NET.Windowing" Version="2.22.0" />
    <PackageReference Include="Silk.NET.Input" Version="2.22.0" />
    <PackageReference Include="Silk.NET.Maths" Version="2.22.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Shaders\Light.vs" CopyToOutputDirectory="PreserveNewest" />
    <None Update="Shaders\Light.ps" CopyToOutputDirectory="PreserveNewest" />
    <None Update="Data\Stone01.tga" CopyToOutputDirectory="PreserveNewest" />
    <None Update="Models\Cube.txt" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
