<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>RastertekCS.Windows.Tutorial19</RootNamespace>
    <AssemblyName>Tutorial19</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Silk.NET.Direct3D11" Version="2.23.0" />
    <PackageReference Include="Silk.NET.Direct3D.Compilers" Version="2.23.0" />
    <PackageReference Include="Silk.NET.DXGI" Version="2.23.0" />
    <PackageReference Include="Silk.NET.Windowing" Version="2.23.0" />
    <PackageReference Include="Silk.NET.Input" Version="2.23.0" />
    <PackageReference Include="Silk.NET.Maths" Version="2.23.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Shaders\AlphaMap.vs" CopyToOutputDirectory="PreserveNewest" />
    <None Update="Shaders\AlphaMap.ps" CopyToOutputDirectory="PreserveNewest" />
    <None
      Include="..\..\Assets\Data\Stone01.tga"
      Link="Data\stone01.tga"
      CopyToOutputDirectory="PreserveNewest"
    />
    <None
      Include="..\..\Assets\Data\dirt01.tga"
      Link="Data\dirt01.tga"
      CopyToOutputDirectory="PreserveNewest"
    />
    <None
      Include="..\..\Assets\Data\alpha01.tga"
      Link="Data\alpha01.tga"
      CopyToOutputDirectory="PreserveNewest"
    />
    <None
      Include="..\..\Assets\Models\square.txt"
      Link="Models\square.txt"
      CopyToOutputDirectory="PreserveNewest"
    />
  </ItemGroup>
</Project>
