client: applicationclass.o cameraclass.o deferredbuffersclass.o deferredshaderclass.o inputclass.o lightclass.o lightshaderclass.o main.o modelclass.o openglclass.o orthowindowclass.o systemclass.o textureclass.o
	g++ -o client applicationclass.o cameraclass.o deferredbuffersclass.o deferredshaderclass.o inputclass.o lightclass.o lightshaderclass.o main.o modelclass.o openglclass.o orthowindowclass.o systemclass.o textureclass.o -l GL -l X11

applicationclass.o: applicationclass.cpp
	g++ -c applicationclass.cpp

cameraclass.o: cameraclass.cpp
	g++ -c cameraclass.cpp

deferredbuffersclass.o: deferredbuffersclass.cpp
	g++ -c deferredbuffersclass.cpp

deferredshaderclass.o: deferredshaderclass.cpp
	g++ -c deferredshaderclass.cpp

inputclass.o: inputclass.cpp
	g++ -c inputclass.cpp

lightclass.o: lightclass.cpp
	g++ -c lightclass.cpp

lightshaderclass.o: lightshaderclass.cpp
	g++ -c lightshaderclass.cpp

main.o: main.cpp
	g++ -c main.cpp

modelclass.o: modelclass.cpp
	g++ -c modelclass.cpp

openglclass.o: openglclass.cpp
	g++ -c openglclass.cpp

orthowindowclass.o: orthowindowclass.cpp
	g++ -c orthowindowclass.cpp

systemclass.o: systemclass.cpp
	g++ -c systemclass.cpp

textureclass.o: textureclass.cpp
	g++ -c textureclass.cpp
