client: applicationclass.o cameraclass.o clutclass.o colorgradeshaderclass.o inputclass.o lightclass.o lightshaderclass.o main.o modelclass.o openglclass.o orthowindowclass.o rendertextureclass.o systemclass.o textureclass.o
	g++ -o client applicationclass.o cameraclass.o clutclass.o colorgradeshaderclass.o inputclass.o lightclass.o lightshaderclass.o main.o modelclass.o openglclass.o orthowindowclass.o rendertextureclass.o systemclass.o textureclass.o -l GL -l X11

applicationclass.o: applicationclass.cpp
	g++ -c applicationclass.cpp

cameraclass.o: cameraclass.cpp
	g++ -c cameraclass.cpp

clutclass.o: clutclass.cpp
	g++ -c clutclass.cpp

colorgradeshaderclass.o: colorgradeshaderclass.cpp
	g++ -c colorgradeshaderclass.cpp

inputclass.o: inputclass.cpp
	g++ -c inputclass.cpp

lightclass.o: lightclass.cpp
	g++ -c lightclass.cpp

lightshaderclass.o: lightshaderclass.cpp
	g++ -c lightshaderclass.cpp

main.o: main.cpp
	g++ -c main.cpp

modelclass.o: modelclass.cpp
	g++ -c modelclass.cpp

openglclass.o: openglclass.cpp
	g++ -c openglclass.cpp

orthowindowclass.o: orthowindowclass.cpp
	g++ -c orthowindowclass.cpp

rendertextureclass.o: rendertextureclass.cpp
	g++ -c rendertextureclass.cpp

systemclass.o: systemclass.cpp
	g++ -c systemclass.cpp

textureclass.o: textureclass.cpp
	g++ -c textureclass.cpp
