client: applicationclass.o cameraclass.o colorshaderclass.o inputclass.o main.o modelclass.o openglclass.o systemclass.o
	g++ -o client applicationclass.o cameraclass.o colorshaderclass.o inputclass.o main.o modelclass.o openglclass.o systemclass.o -l GL -l X11

applicationclass.o: applicationclass.cpp
	g++ -c applicationclass.cpp

cameraclass.o: cameraclass.cpp
	g++ -c cameraclass.cpp

colorshaderclass.o: colorshaderclass.cpp
	g++ -c colorshaderclass.cpp

inputclass.o: inputclass.cpp
	g++ -c inputclass.cpp

main.o: main.cpp
	g++ -c main.cpp

modelclass.o: modelclass.cpp
	g++ -c modelclass.cpp

openglclass.o: openglclass.cpp
	g++ -c openglclass.cpp

systemclass.o: systemclass.cpp
	g++ -c systemclass.cpp
